#!/usr/bin/env python3
"""First-time setup walkthrough (`just bootstrap`).

Stores money-tracker's secrets as fields of one 1Password item (field label = env var name, so
external-secrets and `op run` map them 1:1), then writes .env.op / .env.op.auth: op:// references
only, never values, for local runs via `op run`. Safe to re-run: fields already set are kept unless
you choose to replace them. Nothing here prints a secret.

`--selftest` checks the offline logic without touching 1Password.
"""
import argparse
import base64
import getpass
import json
import os
import secrets
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONCEALED = {"SIMPLEFIN_ACCESS_URL", "SESSION_SECRET", "OIDC_CLIENT_SECRET", "JEV_API_KEY"}
LOCAL_REDIRECT = "http://127.0.0.1:8188/auth/callback"
DEV_FIELDS = ["SIMPLEFIN_ACCESS_URL", "JEV_API_KEY"]  # `just dev-op` runs with AUTH_DISABLED
AUTH_FIELDS = ["OIDC_ISSUER", "OIDC_CLIENT_ID", "OIDC_CLIENT_SECRET", "SESSION_SECRET",
               "OIDC_ALLOWED_EMAILS", "OIDC_ALLOWED_GROUPS"]


def op(*args, stdin=None):
    return subprocess.run(["op", *args], input=stdin, capture_output=True, text=True)


def die(msg):
    sys.exit(f"\n✗ {msg}")


def ask(prompt, default=""):
    got = input(f"{prompt}{f' [{default}]' if default else ''}: ").strip()
    return got or default


def yes(prompt, default=False):
    got = input(f"{prompt} [{'Y/n' if default else 'y/N'}]: ").strip().lower()
    return default if not got else got.startswith("y")


def field_values(item):
    return {f["label"]: f.get("value", "") for f in (item or {}).get("fields", []) if f.get("label")}


def merge(item, title, updates):
    """Item JSON for `op item create -` (item is None) or `op item edit` (item from `op item get --reveal`)."""
    item = json.loads(json.dumps(item)) if item else {"title": title, "category": "SECURE_NOTE", "fields": []}
    by_label = {f.get("label"): f for f in item["fields"]}
    for label, value in updates.items():
        if label in by_label:
            by_label[label]["value"] = value
        else:
            item["fields"].append({"id": label, "label": label, "type": "CONCEALED" if label in CONCEALED else "STRING", "value": value})
    return item


def env_file(vault, title, present, names, extra=()):
    lines = ["# Generated by scripts/bootstrap.py: 1Password references only, no secret values. Use with `op run --env-file`."]
    lines += [f"{n}=op://{vault}/{title}/{n}" for n in names if present.get(n)]
    return "\n".join([*lines, *extra]) + "\n"


class Item:
    def __init__(self, vault, title):
        self.vault, self.title = vault, title
        r = op("item", "get", title, "--vault", vault, "--format", "json", "--reveal")
        if r.returncode == 0:
            self.data = json.loads(r.stdout)
        elif "isn't an item" in r.stderr or "not found" in r.stderr.lower():
            self.data = None
        else:
            die(f"reading {title!r} from vault {vault!r} failed: {r.stderr.strip()}")

    @property
    def values(self):
        return field_values(self.data)

    def save(self, updates):
        body = json.dumps(merge(self.data, self.title, updates))
        if self.data:
            r = op("item", "edit", self.data["id"], "--vault", self.vault, "--format", "json", stdin=body)
        else:
            r = op("item", "create", "--vault", self.vault, "--format", "json", "-", stdin=body)
        if r.returncode != 0:
            raise RuntimeError(r.stderr.strip())
        # Re-read with --reveal: the create/edit output conceals values, and a later edit pipes the whole item back.
        self.__init__(self.vault, self.title)


def want(item, name, why):
    if item.values.get(name):
        return yes(f"{name} is already set. Replace it?")
    print(f"\n{name}: {why}")
    return True


def step_session(item, updates):
    if want(item, "SESSION_SECRET", "signs login cookies; generated here, you never need to see it."):
        updates["SESSION_SECRET"] = base64.b64encode(secrets.token_bytes(32)).decode()


def step_simplefin(item):
    if not want(item, "SIMPLEFIN_ACCESS_URL", "the long-lived SimpleFIN access URL."):
        return
    print("""  1. Sign in at https://beta-bridge.simplefin.org and connect your banks.
  2. Create an app connection and copy its setup token.
  A setup token can be claimed exactly ONCE. The access URL goes straight into 1Password.""")
    if not yes("Have a setup token ready?", True):
        print("  Skipped. Re-run `just bootstrap` when you have one.")
        return
    token = getpass.getpass("  Paste setup token (hidden): ").strip()
    if not token:
        print("  Empty token, skipped.")
        return
    r = subprocess.run(["go", "run", ".", "simplefin-claim"], cwd=ROOT, input=token, capture_output=True, text=True)
    url = r.stdout.strip()
    if r.returncode != 0 or not url.startswith("https://"):
        die(f"claim failed (exit {r.returncode}): {r.stderr.strip() or 'no access URL returned'}\n"
            "  If the token was consumed, create a new one in SimpleFIN Bridge.")
    try:
        item.save({"SIMPLEFIN_ACCESS_URL": url})  # save now: the token is spent, so this URL must not be lost
    except RuntimeError as e:
        rescue = os.path.join(ROOT, "data", "simplefin-access-url.rescue")
        os.makedirs(os.path.dirname(rescue), exist_ok=True)
        fd = os.open(rescue, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as f:
            f.write(url + "\n")
        die(f"saving to 1Password failed ({e}).\n  The access URL was written to {rescue} (mode 600). "
            "Add it to 1Password by hand, then delete that file.")
    print("  ✓ Claimed and saved to 1Password.")


def step_oidc(item, updates):
    print("\nLogin (OIDC via Pocket ID). In Pocket ID > OIDC Clients, create a client (e.g. money-tracker) with")
    print(f"  callback URLs: https://<your-host>/auth/callback and {LOCAL_REDIRECT} (for `just local`)")
    print("  logout callback URLs: https://<your-host>/auth/signed-out and http://127.0.0.1:8188/auth/signed-out")
    if not yes("Set up the login fields now?", True):
        return
    v = item.values
    for name, prompt in [("OIDC_ISSUER", "Pocket ID URL (issuer), e.g. https://id.example.com"),
                         ("OIDC_CLIENT_ID", "Client ID"),
                         ("OIDC_REDIRECT_URL", "Production callback URL, e.g. https://money.example.com/auth/callback"),
                         ("OIDC_ALLOWED_EMAILS", "Allowed emails, comma-separated (blank for none)"),
                         ("OIDC_ALLOWED_GROUPS", "Allowed Pocket ID groups, comma-separated (blank for none)")]:
        got = ask(f"  {prompt}", v.get(name, ""))
        if got != v.get(name, ""):
            updates[name] = got
    if not (updates.get("OIDC_ALLOWED_EMAILS", v.get("OIDC_ALLOWED_EMAILS")) or updates.get("OIDC_ALLOWED_GROUPS", v.get("OIDC_ALLOWED_GROUPS"))):
        print("  ! Neither emails nor groups are allowed: the app will refuse to start with auth on.")
    if not v.get("OIDC_CLIENT_SECRET") or yes("  OIDC_CLIENT_SECRET is set. Replace it?"):
        s = getpass.getpass("  Client secret (hidden; blank for a public PKCE client): ").strip()
        if s:
            updates["OIDC_CLIENT_SECRET"] = s


def step_jev(item, updates):
    if item.values.get("JEV_API_KEY") and not yes("\nJEV_API_KEY is set. Replace it?"):
        return
    if not item.values.get("JEV_API_KEY") and not yes("\nAdd a TypeSafe Jev API key (optional smart suggestions)?"):
        return
    s = getpass.getpass("  Jev API key (hidden): ").strip()
    if s:
        updates["JEV_API_KEY"] = s


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--vault", help="1Password vault (asked if omitted)")
    p.add_argument("--item", default="money-tracker", help="1Password item title (default: money-tracker)")
    p.add_argument("--selftest", action="store_true", help="check the offline logic and exit")
    a = p.parse_args()
    if a.selftest:
        return selftest()

    if op("whoami").returncode != 0:
        die("1Password CLI is not signed in. Unlock the 1Password app with CLI integration on, or run `eval $(op signin)`.")
    vault = a.vault
    if not vault:
        r = op("vault", "list", "--format", "json")
        names = [v["name"] for v in json.loads(r.stdout)] if r.returncode == 0 else []
        print("Vaults:", ", ".join(names) or "(could not list)")
        vault = ask("Vault for money-tracker secrets", "Private" if "Private" in names else "")
    if not vault:
        die("no vault chosen")

    item = Item(vault, a.item)
    print(f"{'Updating' if item.data else 'Creating'} 1Password item {a.item!r} in vault {vault!r}.")

    step_simplefin(item)  # first: it saves immediately, since a claimed token can't be claimed again
    updates = {}
    step_session(item, updates)
    step_oidc(item, updates)
    step_jev(item, updates)
    if updates:
        try:
            item.save(updates)
        except RuntimeError as e:
            die(f"saving to 1Password failed: {e}")
        print(f"\n✓ Saved {', '.join(sorted(updates))} (values not shown).")

    present = item.values
    with open(os.path.join(ROOT, ".env.op"), "w") as f:
        f.write(env_file(vault, a.item, present, DEV_FIELDS))
    with open(os.path.join(ROOT, ".env.op.auth"), "w") as f:
        f.write(env_file(vault, a.item, present, AUTH_FIELDS, [f"OIDC_REDIRECT_URL={LOCAL_REDIRECT}"]))

    print("\nIn 1Password:", ", ".join(sorted(n for n, v in present.items() if v)) or "nothing yet")
    print("Wrote .env.op and .env.op.auth (references only, gitignored).\n")
    print("Next:")
    print("  just demo     poke around with SimpleFIN's public demo data (no secrets, separate database)")
    if present.get("SIMPLEFIN_ACCESS_URL"):
        print("  just dev-op   your real data, hot reload, login off   http://localhost:5188")
    if all(present.get(n) for n in ["OIDC_ISSUER", "OIDC_CLIENT_ID", "SESSION_SECRET"]):
        print("  just local    production-like build with real Pocket ID login   http://127.0.0.1:8188")
    print("Production: DATABASE_URL comes from your Postgres; everything else maps field-for-field from this item.")


def selftest():
    new = merge(None, "money-tracker", {"SESSION_SECRET": "s", "OIDC_ISSUER": "https://id"})
    assert new["category"] == "SECURE_NOTE" and new["title"] == "money-tracker"
    assert {f["label"]: f["type"] for f in new["fields"]} == {"SESSION_SECRET": "CONCEALED", "OIDC_ISSUER": "STRING"}
    existing = {"id": "x", "fields": [{"id": "notesPlain", "label": "notesPlain", "value": ""},
                                      {"id": "a1", "label": "OIDC_ISSUER", "value": "old", "type": "STRING"}]}
    edited = merge(existing, "money-tracker", {"OIDC_ISSUER": "new", "JEV_API_KEY": "k"})
    assert existing["fields"][1]["value"] == "old", "merge must not mutate its input"
    assert field_values(edited) == {"notesPlain": "", "OIDC_ISSUER": "new", "JEV_API_KEY": "k"}
    assert [f["id"] for f in edited["fields"]] == ["notesPlain", "a1", "JEV_API_KEY"], "existing field ids are kept"
    env = env_file("Private", "money-tracker", {"SIMPLEFIN_ACCESS_URL": "SECRETVALUE", "JEV_API_KEY": ""}, DEV_FIELDS, ["A=b"])
    assert "SIMPLEFIN_ACCESS_URL=op://Private/money-tracker/SIMPLEFIN_ACCESS_URL" in env
    assert "JEV_API_KEY" not in env, "empty fields get no reference (op run would fail on it)"
    assert env.endswith("A=b\n") and "SECRETVALUE" not in env, "values never reach the env file"
    print("selftest ok")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        sys.exit("\nAborted. Anything already saved to 1Password stays; re-run to continue.")
